language: node_js

node_js:
  - "0.10"

before_install:
 - sudo apt-get install -y swi-prolog-nox
 - sudo ldconfig
 - pkg-config --list-all
 - pkg-config swipl --cflags
 - pkg-config swipl --cflags-only-I
 - pkg-config swipl --variable=includedir
 - pkg-config swipl --variable=PLBASE
 - ls `pkg-config swipl --variable=PLBASE`
