language: node_js

node_js:
  - "0.10"

before_install:
 - sudo apt-add-repository -y ppa:swi-prolog/devel
 - sudo apt-get install -y swi-prolog-nox
 - pkg-config swipl --cflags
 - pkg-config swipl --cflags-only-I
 - pkg-config swipl --variable=includedir
 - pkg-config swipl --variable=libdir
 - pkg-config swipl --variable=PLBASE
 - sudo ln -v -s `pkg-config swipl --variable=libdir`/swi-prolog `pkg-config swipl --variable=PLBASE`
 - ls `pkg-config swipl --variable=PLBASE`
