language: node_js

node_js:
  - "0.10"

before_install:
 - sudo apt-get install -y swi-prolog-nox
 - sudo ldconfig
 - pkg-config swipl --cflags
 - pkg-config swipl --cflags-only-I
 - ls `pkg-config swipl --cflags-only-I | sed s/^-I//g`
