language: node_js

node_js:
  - "0.10"

before_install:
 - sudo apt-add-repository -y ppa:swi-prolog/devel
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -q
 - sudo apt-get install -y gcc-4.8 g++-4.8 swi-prolog-nox
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
 - sudo update-alternatives --config gcc
 - sudo update-alternatives --config g++
 - pkg-config swipl --cflags
 - pkg-config swipl --cflags-only-I
 - pkg-config swipl --variable=includedir
 - pkg-config swipl --variable=libdir
 - pkg-config swipl --variable=PLBASE
 - gcc -v
 - sudo ln -v -s `pkg-config swipl --variable=libdir`/swi-prolog `pkg-config swipl --variable=PLBASE`
 - ls `pkg-config swipl --variable=PLBASE`
